services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scraper
    ports:
      - "5432:5432"
  
  scraper:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/scraper
    depends_on:
      - db
